### ISSUE TITLE
Searching for cars gives with multi server support sometimes different results.

### ISSUE THREAD

**Issue by Danielvr** [JustaPenguin/assetto-server-manager#1017]
**Describe the bug**
When I search for cars on different servers the results are different. When I look for RSS on server 1 it finds 14 results on server 2 also, but on server 3 it finds 9 and so on. When I look in the list without search all cars exists but the search button is not consistent. Hoewever when it's showing a different number the number will always be the same. With the keywords TCR it works correctly.

**To Reproduce**
Add custom cars to your server and search on the different servers with the same keywords.

**Expected behavior**
Have the same search results on every server.

**Screenshots**
https://imgur.com/a/YRSUmxn

**Comment by cjoneill** [comment]
I suspect the problem here isn't with multiserver per se, rather the `scan_content_folder_for_changes` capability. 

I don't use the multiserver feature but I do have hosts in different geographies using an automated `rsync`-based content replication and this happens often when a significant amount of content (e.g. 6 or 7 cars) is changed on one of the hosts; it only partially appears later in the db on a replica, even allowing ample time for the content to be indexed (e.g. days). Triggering a full search reindex always fixes it.

**Comment by cj123** [comment]
I have a feeling this might only happen if cars are uploaded in batches of more than 1. Can either of you confirm this?

**Comment by cjoneill** [comment]
Missed the ping sorry, but yeah I reckon you've got it in that PR. In some quick tests, only one car was being discovered per batch.
