### ISSUE TITLE
documentation: add reverse proxying (+websockets) to installation instructions

### ISSUE THREAD

**Issue by cj123** [JustaPenguin/assetto-server-manager#696]

**Comment by mazzn** [comment]
Hey, I have ~SSL~ TLS set up for Server Manager on Ubuntu using apache2's mod_reverse_proxy, including working websockets.

Let me know if I can help out and what you're looking for. I could try to write up a basic how-to guide or simply share my apache config with you if needed.

**Comment by cjoneill** [comment]
I've just written a [Wiki page for an Ubuntu/Nginx/Let's Encrypt use case](https://github.com/JustaPenguin/assetto-server-manager/wiki/HTTPS-support-with-an-Nginx-Let's-Encrypt-reverse-proxy-on-Ubuntu). Hopefully that's a start. I think something like that belongs in a Wiki rather than installation instructions, while external packages are required.

**Comment by cj123** [comment]
> I've just written a [Wiki page for an Ubuntu/Nginx/Let's Encrypt use case](https://github.com/JustaPenguin/assetto-server-manager/wiki/HTTPS-support-with-an-Nginx-Let's-Encrypt-reverse-proxy-on-Ubuntu). Hopefully that's a start. I think something like that belongs in a Wiki rather than installation instructions, while external packages are required.

Thanks for this! Just what we needed :) I agree, it belongs in the wiki not the installation file.
